name: Linux Build
on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'
        default: 'v1.0.0'
        type: string
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake gcc g++ clang

    - name: Конфигурация
      run: cmake -B build

    - name: Сборка
      run: cmake --build build

    - name: Создание архивов
      run: |
        cd build
        cpack -G TGZ
        cpack -G ZIP
        cpack -G DEB
        cpack -G RPM

    - name: Загрузка артефактов
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          build/*.tar.gz
          build/*.zip
          build/*.deb
          build/*.rpm
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Установка зависимостей
      run: brew install cmake
    - name: Конфигурация
      run: cmake -B build

    - name: Сборка
      run: cmake --build build

    - name: Создание архивов
      run: |
        cpack -G DragNDrop

    - name: Загрузка артефактов
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          build/*.dmg
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Создание релиза
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          files: |
            build/*.tar.gz
            build/*.zip
            build/*.deb
            build/*.rpm
            build/*.dmg
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

